"""empty message

Revision ID: 1a3426c23351
Revises: 2d52e9be93a7
Create Date: 2015-06-10 17:26:02.669042

"""

# revision identifiers, used by Alembic.
revision = '1a3426c23351'
down_revision = '2d52e9be93a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_date')
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
