"""empty message

Revision ID: 2d52e9be93a7
Revises: 52d81225e3c8
Create Date: 2015-06-08 21:10:45.280073

"""

# revision identifiers, used by Alembic.
revision = '2d52e9be93a7'
down_revision = '52d81225e3c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('extension', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'extension')
    ### end Alembic commands ###
