"""empty message

Revision ID: 3053db039873
Revises: 563bf4213e93
Create Date: 2015-06-18 01:04:51.182440

"""

# revision identifiers, used by Alembic.
revision = '3053db039873'
down_revision = '563bf4213e93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_language_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'language', ['default_language_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'default_language_id')
    ### end Alembic commands ###
