"""empty message

Revision ID: 3503e8578a7c
Revises: 3053db039873
Create Date: 2015-07-11 15:42:53.724286

"""

# revision identifiers, used by Alembic.
revision = '3503e8578a7c'
down_revision = '3053db039873'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
