"""empty message

Revision ID: 4f7ad0fe9c0
Revises: 1df62383e648
Create Date: 2015-06-11 14:16:44.531716

"""

# revision identifiers, used by Alembic.
revision = '4f7ad0fe9c0'
down_revision = '1df62383e648'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippet', 'private')
    ### end Alembic commands ###
