"""empty message

Revision ID: 50da2b5a18f2
Revises: None
Create Date: 2015-06-07 18:49:36.088930

"""

# revision identifiers, used by Alembic.
revision = '50da2b5a18f2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
