"""empty message

Revision ID: 51bdba457f76
Revises: 50da2b5a18f2
Create Date: 2015-06-07 18:52:09.101426

"""

# revision identifiers, used by Alembic.
revision = '51bdba457f76'
down_revision = '50da2b5a18f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
