"""empty message

Revision ID: 52d81225e3c8
Revises: 51bdba457f76
Create Date: 2015-06-08 21:09:33.349009

"""

# revision identifiers, used by Alembic.
revision = '52d81225e3c8'
down_revision = '51bdba457f76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
