"""empty message

Revision ID: 563bf4213e93
Revises: 4f7ad0fe9c0
Create Date: 2015-06-18 01:03:04.054084

"""

# revision identifiers, used by Alembic.
revision = '563bf4213e93'
down_revision = '4f7ad0fe9c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
