"""empty message

Revision ID: 5f680a2429
Revises: 3503e8578a7c
Create Date: 2015-09-20 14:41:48.445072

"""

# revision identifiers, used by Alembic.
revision = '5f680a2429'
down_revision = '3503e8578a7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('parent_fork_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'snippet', 'snippet', ['parent_fork_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snippet', type_='foreignkey')
    op.drop_column('snippet', 'parent_fork_id')
    ### end Alembic commands ###
