"""empty message

Revision ID: 76687fc276c
Revises: 5f680a2429
Create Date: 2015-09-20 14:46:08.051724

"""

# revision identifiers, used by Alembic.
revision = '76687fc276c'
down_revision = '5f680a2429'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
